XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXX
XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXX XXX XX XXXX XXX XXXXXXX XXXXXX XXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXX X XXXX XXXXXXX XXXX XX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXX XXXX XXXX XXXXXX XX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXX
                   XXXXXXXXXXXXX X
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX
                   XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXX
                   XXXXXXXXXXXXX X
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXX
            XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXX X
                      XXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX