# Generated by Django 3.1.5 on 2021-02-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210204_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology'},
        ),
        migrations.AddField(
            model_name='project',
            name='on_page',
            field=models.BooleanField(null=True, verbose_name='Is on displayed on main page ?'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='about_full',
            field=models.TextField(default='', verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='about_short',
            field=models.TextField(default='', verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(help_text='Enter full project description', verbose_name='Full project descritpion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Select related projects', related_name='_project_related_+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='Enter short project description', verbose_name='Short project description'),
        ),
    ]
