# Generated by Django 3.1.5 on 2021-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210205_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='on_page',
            field=models.BooleanField(default=False, verbose_name='Is on displayed on main page ?'),
        ),
    ]
