# Generated by Django 3.1.5 on 2021-04-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/menu-main.html', 'Main - CMS'), ('menus/menu-aside.html', 'Aside - CMS'), ('menus/menu-additional.html', 'Addtional - CMS')], default='', max_length=255, verbose_name='Menu template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page_index.html', 'Index - CMS'), ('page_projects.html', 'Projects'), ('page_project.html', 'Project')], default='', max_length=255, verbose_name='Page template name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('sections/section-footer.html', 'Section Footer - CMS'), ('sections/section-header.html', 'Section Header - CMS'), ('sections/section-welcome.html', 'Section Welcome - CMS'), ('sections/section-stack.html', 'Section Stack - CMS'), ('sections/section-projects.html', 'Section Project Slider - CMS'), ('sections/section-about.html', 'Section About - CMS'), ('sections/section-contact.html', 'Section Contact - CMS'), ('sections/section_projects_filters.html', 'Section Projects Filters'), ('sections/section_projects.html', 'Section Projects'), ('sections/section_project.html', 'Section Project')], default='', max_length=255, verbose_name='Section template name'),
        ),
    ]
