# Generated by Django 3.1.5 on 2021-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0003_auto_20210422_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('sections/section_footer.html', 'Section Footer - Index'), ('sections/section_header.html', 'Section Header - Index'), ('sections/section_welcome.html', 'Section Welcome - Index'), ('sections/section_stack.html', 'Section Stack - Index'), ('sections/section_projects-slider.html', 'Section Project Slider - Index'), ('sections/section_about.html', 'Section About - Index'), ('sections/section_contact.html', 'Section Contact - Index'), ('sections/section_projects_filters.html', 'Section Projects Filters'), ('sections/section_projects.html', 'Section Projects'), ('sections/section_project.html', 'Section Project')], default='', max_length=255, verbose_name='Section template name'),
        ),
    ]
