# Generated by Django 3.1.5 on 2021-05-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0005_auto_20210502_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cms.pagemeta'),
        ),
    ]
