# Generated by Django 3.1.5 on 2021-05-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0007_auto_20210502_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemeta',
            name='id_name',
        ),
    ]
