# Generated by Django 3.1.5 on 2021-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0008_remove_pagemeta_id_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagemeta',
            table='app_cms_page_meta',
        ),
        migrations.AlterModelTable(
            name='pagemetatranslation',
            table='app_cms_page_meta_translation',
        ),
    ]
