# Generated by Django 3.1.5 on 2021-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0009_auto_20210502_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemetatranslation',
            name='description',
        ),
        migrations.AddField(
            model_name='pagemetatranslation',
            name='meta_description',
            field=models.CharField(default=',', max_length=255, verbose_name='Page meta description'),
        ),
        migrations.AddField(
            model_name='pagemetatranslation',
            name='meta_title',
            field=models.CharField(default='', max_length=55, verbose_name='Page meta title'),
        ),
        migrations.AlterField(
            model_name='pagemetatranslation',
            name='title',
            field=models.CharField(default='', max_length=55, verbose_name='Page title'),
        ),
    ]
