# Generated by Django 3.1.5 on 2025-03-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0011_pagemetatranslation_json_ld'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        )
    ]
