from .contact_admin import *
from .cv_admin import *
from .cv_doc_admin import *
from .cv_doc_contact_admin import *
from .cv_doc_personal_admin import *
from .cv_doc_edu_admin import *
from .cv_doc_exp_admin import *
from .cv_doc_photo_admin import *
from .cv_doc_skills_admin import *
from .cv_doc_sum_admin import *
from .cv_doc_additional_admin import *
from .cv_doc_agreements_admin import *
from .cv_color_profile_admin import *