from .contact_admin import *
from .cv_admin import *
from .cv_doc_admin import *
from .cv_doc_contact_admin import *
from .cv_doc_edu_admin import *
from .cv_doc_exp_admin import *
from .cv_doc_skills_admin import *
from .cv_doc_sum_admin import *
from .cv_doc_additional_admin import *