# Generated by Django 3.1.5 on 2021-01-25 23:07

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import projects.models.project_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('surname', models.CharField(default='', max_length=255, verbose_name='Surname')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('about_short', models.TextField(default='', max_length=255, verbose_name='Short description')),
                ('about_full', models.TextField(default='', max_length=1000, verbose_name='Full description')),
                ('photo', models.ImageField(help_text='Select author photo', max_length=255, upload_to='author', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter project name', max_length=100, verbose_name='Project name')),
                ('short_description', models.TextField(help_text='Enter short project description', max_length=255, verbose_name='Short project description')),
                ('full_description', models.TextField(help_text='Enter full project description', max_length=1000, verbose_name='Full project descritpion')),
                ('repository', models.CharField(help_text='Enter url of project repository', max_length=500, verbose_name='Repository')),
                ('demo', models.CharField(help_text='Enter url of demo page', max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.owner')),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', help_text='Enter technology name', max_length=255)),
                ('description', models.CharField(blank=True, default='Description', help_text='Enter technology description', max_length=255, null=True)),
                ('is_main', models.BooleanField(verbose_name='Is owner main technology ?')),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Skill rete')),
                ('logo', models.ImageField(max_length=255, upload_to='technology')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Order weight')),
            ],
            options={
                'verbose_name': 'Technology',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=projects.models.project_image.user_directory_path, width_field='width')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Select technology for this project', to='projects.Technology'),
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter portal name', max_length=100, verbose_name='Portal name')),
                ('url', models.CharField(help_text='Enter portal profile url', max_length=255, verbose_name='Owner profile url')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', help_text='Portal logo expect 100 x 100 px', keep_meta=True, quality=0, size=[500, 300], upload_to='portals', verbose_name='Portal logo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.owner')),
            ],
            options={
                'verbose_name': 'Owner Portal',
            },
        ),
    ]
