# Generated by Django 3.1.5 on 2021-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210204_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Select related projects', null=True, related_name='_project_related_+', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('LIB', 'Library'), ('API', 'Api'), ('WEB', 'Webpage')], default='WEB', max_length=3),
        ),
    ]
