# Generated by Django 3.1.5 on 2021-03-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0002_auto_20210311_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='menus',
            new_name='menu',
        ),
    ]
