# Generated by Django 3.1.5 on 2021-03-11 04:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0003_auto_20210311_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='text',
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Menu item text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='app_index.menuitem')),
            ],
            options={
                'verbose_name': 'menu item Translation',
                'db_table': 'app_index_menuitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
