# Generated by Django 3.1.5 on 2021-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0004_auto_20210311_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='template',
            field=models.CharField(default='', max_length=255, verbose_name='Menu template'),
        ),
    ]
