# Generated by Django 3.1.5 on 2021-03-12 01:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0005_menu_template'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='propertytextlong',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='propertytextrich',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='propertytextlong',
            name='value',
        ),
        migrations.RemoveField(
            model_name='propertytextrich',
            name='value',
        ),
        migrations.CreateModel(
            name='PropertyTextRichTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.TextField(default='', verbose_name='Text value')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_index.propertytextrich')),
            ],
            options={
                'verbose_name': 'Property Text Rich Translation',
                'db_table': 'app_index_propertytextrich_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyTextLongTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.TextField(default='', verbose_name='Text value')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_index.propertytextlong')),
            ],
            options={
                'verbose_name': 'Property Text Long Translation',
                'db_table': 'app_index_propertytextlong_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
