# Generated by Django 3.1.5 on 2021-03-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0006_auto_20210312_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='style',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('includes/footer.html', 'Footer'), ('includes/header.html', 'Header'), ('includes/menu-aside.html', 'Menu Aside'), ('includes/menu-main.html', 'Menu main'), ('includes/section-welcome.html', 'Section Welcome'), ('includes/section-stack.html', 'Section Stack'), ('includes/section-projects.html', 'Section Project'), ('includes/section-about.html', 'Section About'), ('includes/section-contact.html', 'Section Contact')], default='', max_length=255, verbose_name='Section template name'),
        ),
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(choices=[('project', 'Project')], default='', max_length=255, null=True),
        ),
    ]
