# Generated by Django 3.1.5 on 2021-03-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0007_auto_20210313_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'Section'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='position',
        ),
    ]
