# Generated by Django 3.1.5 on 2021-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0009_auto_20210313_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='address',
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page_index.html', 'Index')], default='', max_length=255, verbose_name='Page template name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('sections/section-footer.html', 'Section Footer'), ('sections/section-header.html', 'Section Header'), ('sections/section-welcome.html', 'Section Welcome'), ('sections/section-stack.html', 'Section Stack'), ('sections/section-projects.html', 'Section Project'), ('sections/section-about.html', 'Section About'), ('sections/section-contact.html', 'Section Contact')], default='', max_length=255, verbose_name='Section template name'),
        ),
    ]
