# Generated by Django 3.1.5 on 2021-03-13 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0010_auto_20210313_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255, unique=True, verbose_name='Pager url address'), default=[], size=None),
            preserve_default=False,
        ),
    ]
