# Generated by Django 3.1.5 on 2021-03-13 23:37

from django.db import migrations, models
import django.db.models.deletion
import parler

class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0012_auto_20210313_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='address',
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, verbose_name='Regex path pattern - groups as parameters')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_index.page')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model,),
        ),
    ]
