# Generated by Django 3.1.5 on 2021-03-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0014_path_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='Regex url pattern - groups as parameters'),
        ),
    ]
