# Generated by Django 3.1.5 on 2021-03-14 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0016_auto_20210314_0443'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='path',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='path',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='path',
            name='url',
        ),
        migrations.CreateModel(
            name='PathTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(max_length=255, verbose_name='Regex path pattern - groups as parameters')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='app_index.path')),
            ],
            options={
                'verbose_name': 'path Translation',
                'db_table': 'app_index_path_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(models.Model,),
        ),
    ]
