# Generated by Django 3.1.5 on 2021-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0017_auto_20210314_0602'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='path',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='pattern',
            field=models.CharField(default='', max_length=255, verbose_name='Regex path pattern - groups as parameters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='path',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regex url pattern - groups as parameters'),
        ),
        migrations.DeleteModel(
            name='PathTranslation',
        ),
    ]
