# Generated by Django 3.1.5 on 2021-03-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0018_auto_20210314_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(choices=[('app_index.views.section_projects.py', 'Section projects')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='app_index.section'),
        ),
    ]
