# Generated by Django 3.1.5 on 2021-03-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0025_auto_20210315_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemtranslation',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='view',
            name='config',
            field=models.JSONField(default='{}', verbose_name='View json configuration'),
            preserve_default=False,
        ),
    ]
