# Generated by Django 3.1.5 on 2021-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0026_auto_20210315_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='config',
            field=models.JSONField(default=dict, verbose_name='View json configuration'),
        ),
    ]
