# Generated by Django 3.1.5 on 2021-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0027_auto_20210315_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page_index.html', 'Index'), ('page_projects.html', 'Projects'), ('page_project.html', 'Project')], default='', max_length=255, verbose_name='Page template name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('sections/section-footer.html', 'Section Footer'), ('sections/section-header.html', 'Section Header'), ('sections/section-welcome.html', 'Section Welcome'), ('sections/section-stack.html', 'Section Stack'), ('sections/section-projects.html', 'Section Project Slider'), ('sections/section-about.html', 'Section About'), ('sections/section-contact.html', 'Section Contact'), ('sections/section_projects_filters.html', 'Section Projects Filters'), ('sections/section_projects.html', 'Section Projects'), ('sections/section_project.html', 'Section Project')], default='', max_length=255, verbose_name='Section template name'),
        ),
        migrations.AlterField(
            model_name='view',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='View json configuration'),
        ),
    ]
