# Generated by Django 3.1.5 on 2021-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0028_auto_20210316_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='module_name',
            field=models.CharField(choices=[('app_index.views.section_projects.py', 'Section projects'), ('app_owner.views.section_contact.py', 'Section contact')], default='', max_length=255, null=True),
        ),
    ]
