# Generated by Django 3.1.5 on 2021-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0031_pathtranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='view',
            name='module_name',
            field=models.CharField(choices=[], default='', max_length=255, null=True),
        ),
    ]
