# Generated by Django 3.1.5 on 2021-03-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0032_auto_20210319_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='module_name',
            field=models.CharField(choices=[('app_projects.views.section_projects.py', 'Section projects'), ('app_owner.views.section_contact.py', 'Section contact')], default='', max_length=255, null=True),
        ),
    ]
