# Generated by Django 3.1.5 on 2021-03-19 08:41

from django.db import migrations, models
import django.db.models.deletion
import imagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Identification name')),
            ],
            options={
                'verbose_name': 'Project gallery',
                'db_table': 'app_projects_project_gallery',
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagefield.fields.ImageField(height_field='height', upload_to='', verbose_name='Image', width_field='width')),
                ('width', models.PositiveIntegerField(verbose_name='Image width')),
                ('height', models.PositiveIntegerField(verbose_name='Image height')),
                ('image_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.projectgallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'db_table': 'app_projects_project_gallery_image',
            },
        ),
    ]
