# Generated by Django 3.1.5 on 2021-03-19 09:06

from django.db import migrations
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=imagefield.fields.ImageField(height_field='height', upload_to='project_gallery/', verbose_name='Image', width_field='width'),
        ),
    ]
