# Generated by Django 3.1.5 on 2021-03-19 09:28

from django.db import migrations
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_auto_20210319_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='image_ppoi',
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20, verbose_name='Image PPOI'),
        ),
    ]
