# Generated by Django 3.1.5 on 2021-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0003_auto_20210319_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgalleryimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
