# Generated by Django 3.1.5 on 2021-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0004_projectgalleryimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
