# Generated by Django 3.1.5 on 2021-03-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0005_auto_20210319_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'verbose_name': 'Project gallery', 'verbose_name_plural': 'Project galleries'},
        ),
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
