# Generated by Django 3.1.5 on 2021-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0007_auto_20210319_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Release date'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_date',
            field=models.DateField(null=True, verbose_name='Last update date'),
        ),
    ]
