# Generated by Django 3.1.5 on 2021-03-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0008_auto_20210319_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_projects.projectgallery', verbose_name='Gallery'),
            preserve_default=False,
        ),
    ]
