# Generated by Django 3.1.5 on 2021-03-19 13:19

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0009_project_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related',
            field=models.ManyToManyField(to='app_projects.Project', verbose_name='Related'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Link'), size=None),
        ),
    ]
