# Generated by Django 3.1.5 on 2021-03-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0010_auto_20210319_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_full',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
