# Generated by Django 3.1.5 on 2021-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0012_projecttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project title'),
        ),
    ]
