# Generated by Django 3.1.5 on 2021-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0013_auto_20210319_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'verbose_name': 'Project gallery', 'verbose_name_plural': 'Projects gallery'},
        ),
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.RemoveField(
            model_name='technologytype',
            name='name',
        ),
    ]
