# Generated by Django 3.1.5 on 2021-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0015_technologytypetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='show_on_index_all',
            field=models.BooleanField(default=False, verbose_name='Show on main page in all section'),
        ),
    ]
