# Generated by Django 3.1.5 on 2021-03-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0018_auto_20210319_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_projects.projecttype'),
            preserve_default=False,
        ),
    ]
