# Generated by Django 3.1.5 on 2021-03-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0020_auto_20210320_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#000000', max_length=36, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
