# Generated by Django 3.1.5 on 2021-03-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0022_auto_20210320_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='display',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
