# Generated by Django 3.1.5 on 2021-03-21 11:08

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0023_projecttype_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
