# Generated by Django 3.1.5 on 2021-03-23 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0025_projectsearchautocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='autocomplete_hint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='hint'), blank=True, null=True, size=None),
        ),
    ]
