# Generated by Django 3.1.5 on 2021-03-23 12:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0027_auto_20210323_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='autocomplete_hint',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='hint'), blank=True, null=True, size=None, verbose_name='Autocomplete hint'),
        ),
    ]
