# Generated by Django 3.1.5 on 2021-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0028_auto_20210323_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsearchautocomplete',
            name='source_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsearchautocomplete',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
