# Generated by Django 3.1.5 on 2021-03-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0029_auto_20210323_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsearchautocomplete',
            name='term',
            field=models.TextField(),
        ),
    ]
