# Generated by Django 3.1.5 on 2021-03-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0030_auto_20210325_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlink',
            old_name='links',
            new_name='url',
        ),
    ]
