# Generated by Django 3.1.5 on 2021-03-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0031_auto_20210325_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologytype',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
