# Generated by Django 3.1.5 on 2021-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0032_technologytype_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologytype',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight'),
        ),
    ]
