# Generated by Django 3.1.5 on 2021-03-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0033_auto_20210326_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologyimage',
            old_name='contact',
            new_name='technology',
        ),
    ]
