# Generated by Django 3.1.5 on 2021-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0034_auto_20210326_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_on_index',
            field=models.BooleanField(default=False, verbose_name='Show on main page'),
        ),
    ]
