# Generated by Django 3.1.5 on 2021-05-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0039_project_sort_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_weight'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
