# Generated by Django 3.1.5 on 2021-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0042_projectgalleryimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='json_ld',
            field=models.JSONField(blank=True, null=True, verbose_name='Json ld'),
        ),
    ]
