# Generated by Django 3.1.5 on 2021-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0044_auto_20210515_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_type',
            field=models.CharField(blank=True, choices=[('BrowserApplication', 'Browser Application'), ('BusinessApplication', 'Business Application'), ('CommunicationApplication', 'Communication Application'), ('DesignApplication', 'Design Application'), ('DesktopEnhancementApplication', 'Desktop Enhancement Application'), ('DeveloperApplication', 'Developer Application'), ('DriverApplication', 'Driver Application'), ('EducationalApplication', 'Educational Application'), ('EntertainmentApplication', 'Entertainment Application'), ('FinanceApplication', 'Finance Application'), ('GameApplication', 'Game Application'), ('HealthApplication', 'Health Application'), ('HomeApplication', 'Home Application'), ('LifestyleApplication', 'Lifestyle Application'), ('MultimediaApplication', 'Multimedia Application'), ('ReferenceApplication', 'Reference Application'), ('SecurityApplication', 'Security Application'), ('ShoppingApplication', 'Shopping Application'), ('SocialNetworkingApplication', 'Social Networking Application'), ('SportsApplication', 'Sports Application'), ('TravelApplication', 'Travel Application'), ('UtilitiesApplication', 'Utilities Application')], default='UtilitiesApplication', max_length=100, null=True, verbose_name='Seo app type'),
        ),
    ]
