# Generated by Django 3.1.5 on 2021-05-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0045_auto_20210515_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='app_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='op_system',
            new_name='operating_system',
        ),
    ]
