# Generated by Django 3.1.5 on 2025-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0047_auto_20210515_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight'),
        ),
    ]
