# Generated by Django 3.1.5 on 2025-04-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0048_technology_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='weight_cv',
            field=models.IntegerField(default=0, verbose_name='WeightCV'),
        ),
    ]
