BBBB BBBBBBBBB
BBBBBBBB BBBBBBBBBBBBBBBB BB BBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX
            FFFF
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX
    XXXXXX
XXXXXX
