# Generated by Django 3.1.5 on 2021-03-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Menu identification name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Menu description')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Page name')),
                ('address', models.CharField(default='', max_length=255, unique=True, verbose_name='Pager url address')),
                ('template', models.CharField(default='', max_length=255, verbose_name='Page template name')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='only letters', max_length=255, unique=True, verbose_name='Section identification name')),
                ('template', models.CharField(default='', max_length=255, verbose_name='Section template name')),
                ('view', models.CharField(default='', max_length=255, verbose_name='Section view')),
                ('order_weight', models.PositiveIntegerField(verbose_name='Order')),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_index.page')),
            ],
            options={
                'verbose_name': 'Section',
                'ordering': ['order_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Variable name')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_index.section')),
            ],
            options={
                'verbose_name': 'Variable',
            },
        ),
        migrations.CreateModel(
            name='VariableText',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_index.variable')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Text value')),
            ],
            options={
                'verbose_name': 'Variable Text',
            },
            bases=('app_index.variable',),
        ),
        migrations.CreateModel(
            name='VariableTextLong',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_index.variable')),
                ('value', models.TextField(default='', verbose_name='Text value')),
            ],
            options={
                'verbose_name': 'Variable Text Long',
            },
            bases=('app_index.variable',),
        ),
        migrations.CreateModel(
            name='VariableTextRich',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_index.variable')),
                ('value', models.TextField(default='', verbose_name='Text value')),
            ],
            options={
                'verbose_name': 'Variable Text Rich',
            },
            bases=('app_index.variable',),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255, verbose_name='Text')),
                ('url', models.CharField(default='', max_length=255, verbose_name='Url')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_index.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_index.page'),
        ),
    ]
