# Generated by Django 3.1.5 on 2021-03-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Section'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='order_weight',
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
