# Generated by Django 3.1.5 on 2021-03-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.CreateModel(
            name='PageSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_index.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_index.section')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ManyToManyField(through='app_index.PageSections', to='app_index.Section', verbose_name='Page sections'),
        ),
    ]
