# Generated by Django 3.1.5 on 2021-03-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_index', '0002_auto_20210308_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='page',
        ),
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='menus',
            field=models.ManyToManyField(blank=True, to='app_index.Menu', verbose_name='Page menus'),
        ),
        migrations.AddField(
            model_name='variable',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app_index.variable_set+', to='contenttypes.contenttype'),
        ),
    ]
