# Generated by Django 3.1.5 on 2021-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0003_auto_20210309_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ManyToManyField(blank=True, to='app_index.Section', verbose_name='Page sections'),
        ),
    ]
