# Generated by Django 3.1.5 on 2021-03-09 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0004_page_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_index.page'),
        ),
    ]
