# Generated by Django 3.1.5 on 2021-03-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0005_auto_20210309_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='view',
        ),
    ]
