# Generated by Django 3.1.5 on 2021-03-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0008_auto_20210313_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='style',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/menu-main.html', 'Main'), ('menus/menu-aside.html', 'Aside')], default='', max_length=255, verbose_name='Menu template'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('includes/section-footer.html', 'Section Footer'), ('includes/section-header.html', 'Section Header'), ('includes/section-welcome.html', 'Section Welcome'), ('includes/section-stack.html', 'Section Stack'), ('includes/section-projects.html', 'Section Project'), ('includes/section-about.html', 'Section About'), ('includes/section-contact.html', 'Section Contact')], default='', max_length=255, verbose_name='Section template name'),
        ),
    ]
