# Generated by Django 3.1.5 on 2021-03-13 11:42

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0011_page_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='address',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(default='', max_length=255, unique=True, verbose_name='Pager url address'), size=None),
        ),
    ]
