# Generated by Django 3.1.5 on 2021-03-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0013_auto_20210314_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Regex url pattern - groups as parameters'),
            preserve_default=False,
        ),
    ]
