# Generated by Django 3.1.5 on 2021-03-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0015_auto_20210314_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regex url pattern - groups as parameters'),
        ),
    ]
