# Generated by Django 3.1.5 on 2021-03-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0019_auto_20210314_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='name',
            new_name='module_name',
        ),
    ]
