# Generated by Django 3.1.5 on 2021-03-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0020_auto_20210314_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/menu-main.html', 'Main'), ('menus/menu-aside.html', 'Aside'), ('menus/menu-additional.html', 'Addtional')], default='', max_length=255, verbose_name='Menu template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page_index.html', 'Index'), ('page_projects.html', 'Projects')], default='', max_length=255, verbose_name='Page template name'),
        ),
    ]
