# Generated by Django 3.1.5 on 2021-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0023_auto_20210315_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemtranslation',
            name='t_url',
            field=models.CharField(default='', max_length=255, verbose_name='Url'),
        ),
    ]
