# Generated by Django 3.1.5 on 2021-03-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0024_menuitemtranslation_t_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemtranslation',
            name='t_url',
        ),
    ]
