# Generated by Django 3.1.5 on 2021-03-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0029_auto_20210316_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='path',
            name='url',
        ),
    ]
