# Generated by Django 3.1.5 on 2021-03-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sprite', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app_owner.contactimage_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Standalone image',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Contact name')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_owner.contactimage')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app_owner.contact_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='ContactImageSprite',
            fields=[
                ('contactimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.contactimage')),
                ('top', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Top')),
                ('left', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Left')),
                ('width', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Width')),
                ('height', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Height')),
            ],
            options={
                'verbose_name': 'Sprite image',
            },
            bases=('app_owner.contactimage',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='portals', width_field='width')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('contact_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.contactimage')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.contact')),
                ('number', models.CharField(max_length=30, verbose_name='Contact number')),
            ],
            options={
                'verbose_name': 'Contact number',
            },
            bases=('app_owner.contact',),
        ),
        migrations.CreateModel(
            name='ContactPortal',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.contact')),
                ('url', models.CharField(max_length=1000, verbose_name='Contact url')),
            ],
            options={
                'verbose_name': 'Contact url',
            },
            bases=('app_owner.contact',),
        ),
    ]
