# Generated by Django 3.1.5 on 2021-03-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0002_auto_20210316_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactimage',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_owner.contact'),
        ),
    ]
