# Generated by Django 3.1.5 on 2021-03-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0003_auto_20210316_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImageStandalone',
            fields=[
                ('contactimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.contactimage')),
            ],
            options={
                'verbose_name': 'Contact image standalone',
            },
            bases=('app_owner.contactimage',),
        ),
        migrations.AlterModelOptions(
            name='contactimage',
            options={'verbose_name': 'Contact image'},
        ),
        migrations.AlterField(
            model_name='image',
            name='contact_img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_owner.contactimage'),
        ),
    ]
