# Generated by Django 3.1.5 on 2021-03-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0004_auto_20210316_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='contact_img',
        ),
        migrations.AddField(
            model_name='contactimage',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_owner.image'),
            preserve_default=False,
        ),
    ]
