# Generated by Django 3.1.5 on 2021-03-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0006_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactimagestandalone',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='contactportal',
            options={'verbose_name': 'Contact portal'},
        ),
        migrations.AlterField(
            model_name='contactimagesprite',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='contactimagesprite',
            name='left',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='contactimagesprite',
            name='top',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Top'),
        ),
        migrations.AlterField(
            model_name='contactimagesprite',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Width'),
        ),
    ]
