# Generated by Django 3.1.5 on 2021-03-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0007_auto_20210316_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order weight'),
        ),
    ]
