# Generated by Django 3.1.5 on 2021-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0008_contact_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order'], 'verbose_name': 'Contact'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order weight'),
        ),
    ]
