# Generated by Django 3.1.5 on 2021-03-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0009_auto_20210316_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(verbose_name='Order weight'),
        ),
    ]
