# Generated by Django 3.1.5 on 2021-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0011_auto_20210316_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Weight'),
        ),
    ]
