# Generated by Django 3.1.5 on 2021-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0012_auto_20210316_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
    ]
