# Generated by Django 3.1.5 on 2021-03-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0012_auto_20210316_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.contact')),
                ('address', models.TextField(default='', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Contact address',
            },
            bases=('app_owner.contact',),
        ),
        migrations.AddField(
            model_name='contact',
            name='show_on_index',
            field=models.BooleanField(default=True, verbose_name='Show on main page'),
        ),
    ]
