# Generated by Django 3.1.5 on 2021-03-29 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_better_admin_arrayfield.models.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0035_project_show_on_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_owner', '0014_auto_20210328_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocumentAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Identification name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'CV document additional info',
                'verbose_name_plural': 'CV document additional infos',
                'db_table': 'app_owner_cv_doc_add',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Identification name')),
            ],
            options={
                'verbose_name': 'CV document education',
                'verbose_name_plural': 'CV documents educations',
                'db_table': 'app_owner_cv_doc_edu',
            },
        ),
        migrations.CreateModel(
            name='CVDocumentEducationSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.cvdocumenteducation')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'app_owner_cv_doc_edu_school',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Identification name')),
            ],
            options={
                'verbose_name': 'CV document experience',
                'verbose_name_plural': 'CV documents experiences',
                'db_table': 'app_owner_cv_doc_exp',
            },
        ),
        migrations.CreateModel(
            name='CVDocumentExperienceJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.cvdocumentexperience')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'app_owner_cv_doc_exp_job',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Skill',
                'db_table': 'app_owner_cv_doc_skill',
            },
        ),
        migrations.CreateModel(
            name='CVDocumentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Identification name')),
            ],
            options={
                'verbose_name': 'CV document Summary',
                'db_table': 'app_owner_cv_doc_sum',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentSkillLanguage',
            fields=[
                ('cvdocumentskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.cvdocumentskill')),
                ('level', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], max_length=50, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Skill',
                'db_table': 'app_owner_cv_doc_skill_lang',
            },
            bases=('app_owner.cvdocumentskill', parler.models.TranslatableModelMixin, models.Model),
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CVDocumentSkillOther',
            fields=[
                ('cvdocumentskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_owner.cvdocumentskill')),
                ('level', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'app_owner_cv_doc_skill_other',
            },
            bases=('app_owner.cvdocumentskill', parler.models.TranslatableModelMixin, models.Model),
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CVDocumentSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Identification name')),
                ('technologies', models.ManyToManyField(to='app_projects.Technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Document skills',
                'verbose_name_plural': 'Documents skills',
                'db_table': 'app_owner_cv_doc_skills',
            },
        ),
        migrations.AddField(
            model_name='cvdocumentskill',
            name='document_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.cvdocumentskills'),
        ),
        migrations.AddField(
            model_name='cvdocumentskill',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app_owner.cvdocumentskill_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='CVDocumentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('contacts', models.ManyToManyField(to='app_owner.Contact', verbose_name='Contacts')),
            ],
            options={
                'verbose_name': 'CV Document contact',
                'db_table': 'app_owner_cv_doc_contact',
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Identification name')),
                ('additional', models.ManyToManyField(to='app_owner.CVDocumentAdditional', verbose_name='Skills')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentcontact', verbose_name='Contact data')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumenteducation', verbose_name='Education')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentexperience', verbose_name='Experience')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentskills', verbose_name='Skills')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentsummary', verbose_name='Summary')),
            ],
            options={
                'verbose_name': 'CV Document',
                'verbose_name_plural': 'CV Documents',
                'db_table': 'app_owner_cv_doc',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Version name')),
                ('template', models.CharField(blank=True, choices=[('test', 'test')], max_length=255, verbose_name='PDF template')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocument')),
            ],
            options={
                'verbose_name': 'CV PDF',
                'verbose_name_plural': 'CV PDFs',
            },
        ),
        migrations.CreateModel(
            name='CVDocumentSummaryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('summary_title', models.CharField(max_length=255, verbose_name='Summary section tittle')),
                ('summary_content', models.TextField(verbose_name='Summary content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_owner.cvdocumentsummary')),
            ],
            options={
                'verbose_name': 'CV document Summary Translation',
                'db_table': 'app_owner_cv_doc_sum_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentExperienceJobTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(verbose_name='Description'), size=None)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='app_owner.cvdocumentexperiencejob')),
            ],
            options={
                'verbose_name': 'Job Translation',
                'db_table': 'app_owner_cv_doc_exp_job_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentEducationSchoolTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('school', models.CharField(max_length=255, verbose_name='School name')),
                ('field', models.TextField(max_length=255, verbose_name='Field of study')),
                ('description', models.TextField(verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='app_owner.cvdocumenteducationschool')),
            ],
            options={
                'verbose_name': 'School Translation',
                'db_table': 'app_owner_cv_doc_edu_school_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentAdditionalTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('items', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Items'), size=None)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='app_owner.cvdocumentadditional')),
            ],
            options={
                'verbose_name': 'CV document additional info Translation',
                'db_table': 'app_owner_cv_doc_add_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentSkillOtherTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.TextField(verbose_name='Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_owner.cvdocumentskillother')),
            ],
            options={
                'verbose_name': 'Skill Translation',
                'db_table': 'app_owner_cv_doc_skill_other_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVDocumentSkillLanguageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Language name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_owner.cvdocumentskilllanguage')),
            ],
            options={
                'verbose_name': 'Skill Translation',
                'db_table': 'app_owner_cv_doc_skill_lang_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
