# Generated by Django 3.1.5 on 2021-03-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0015_auto_20210330_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocumentcontact',
            name='contacts',
        ),
        migrations.CreateModel(
            name='CVDocumentContactContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.contact')),
                ('document_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.cvdocumentcontact')),
            ],
            options={
                'db_table': 'app_owner_cv_doc_contact_contacts_rel',
            },
        ),
    ]
