# Generated by Django 3.1.5 on 2021-03-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0016_auto_20210330_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocumentcontact',
            name='contacts',
            field=models.ManyToManyField(through='app_owner.CVDocumentContactContacts', to='app_owner.Contact', verbose_name='Contacts'),
        ),
    ]
