# Generated by Django 3.1.5 on 2021-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0017_cvdocumentcontact_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdocumenteducationschooltranslation',
            name='field',
            field=models.CharField(max_length=255, verbose_name='Field of study'),
        ),
    ]
