# Generated by Django 3.1.5 on 2021-03-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0018_auto_20210330_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocumentexperience',
            old_name='name',
            new_name='id_name',
        ),
    ]
