# Generated by Django 3.1.5 on 2021-03-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0019_auto_20210330_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocument',
            old_name='name',
            new_name='id_name',
        ),
        migrations.RenameField(
            model_name='cvdocumentadditional',
            old_name='name',
            new_name='id_name',
        ),
        migrations.RenameField(
            model_name='cvdocumentcontact',
            old_name='name',
            new_name='id_name',
        ),
        migrations.RenameField(
            model_name='cvdocumenteducation',
            old_name='name',
            new_name='id_name',
        ),
        migrations.RenameField(
            model_name='cvdocumentskills',
            old_name='name',
            new_name='id_name',
        ),
        migrations.RenameField(
            model_name='cvdocumentsummary',
            old_name='name',
            new_name='id_name',
        ),
    ]
