# Generated by Django 3.1.5 on 2021-03-30 21:15

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0035_project_show_on_index'),
        ('app_owner', '0020_auto_20210330_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdocumentskills',
            name='technologies',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='app_projects.Technology', verbose_name='Technologies'),
        ),
    ]
