# Generated by Django 3.1.5 on 2021-03-30 22:21

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0021_auto_20210330_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvdocumentskilllanguage',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='cvdocumentskilllanguagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Language Translation'},
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='additional',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='app_owner.CVDocumentAdditional', verbose_name='Skills'),
        ),
    ]
