# Generated by Django 3.1.5 on 2021-03-31 03:42

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0022_auto_20210331_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocumentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Photo identification name')),
                ('source', models.ImageField(height_field='height', upload_to='cv-photo', width_field='width')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'app_owner_cv_doc_photo',
            },
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='additional',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='app_owner.CVDocumentAdditional', verbose_name='Additional'),
        ),
        migrations.AlterField(
            model_name='cvdocumentadditional',
            name='type',
            field=models.CharField(choices=[('hobby', 'Hobby'), ('other', 'Other')], max_length=50, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='photo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentphoto', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
