# Generated by Django 3.1.5 on 2021-03-31 03:53

from django.db import migrations, models
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0023_auto_20210331_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocumentphoto',
            name='ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AlterField(
            model_name='cvdocumentphoto',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Image height'),
        ),
        migrations.AlterField(
            model_name='cvdocumentphoto',
            name='source',
            field=imagefield.fields.ImageField(height_field='height', upload_to='cv-photo/', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='cvdocumentphoto',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Image width'),
        ),
    ]
