# Generated by Django 3.1.5 on 2021-03-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0024_auto_20210331_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocumentphoto',
            old_name='name',
            new_name='id_name',
        ),
    ]
