# Generated by Django 3.1.5 on 2021-03-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0025_auto_20210331_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVDocumentContact',
            new_name='CVDocumentPersonal',
        ),
        migrations.RenameField(
            model_name='cvdocument',
            old_name='contact',
            new_name='personal',
        ),
    ]
