# Generated by Django 3.1.5 on 2021-03-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0026_auto_20210331_0631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVDocumentContactContacts',
            new_name='CVDocumentPersonalContacts',
        ),
    ]
