# Generated by Django 3.1.5 on 2021-03-31 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0028_auto_20210331_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocument',
            name='photo',
        ),
        migrations.AddField(
            model_name='cvdocumentpersonal',
            name='photo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentphoto', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
