# Generated by Django 3.1.5 on 2021-03-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0031_auto_20210331_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='document_title',
            field=models.CharField(blank=True, help_text='If not present default: Name + Surname', max_length=255, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='download_name',
            field=models.CharField(blank=True, help_text='If not present default: Name + Surname', max_length=255, verbose_name='Document download filename'),
        ),
        migrations.AlterField(
            model_name='cvdocumentpersonal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
