# Generated by Django 3.1.5 on 2021-04-07 16:05

import app_owner.models.cv_color_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0032_auto_20210331_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVColorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=255, verbose_name='Color profile identification name')),
                ('primary', app_owner.models.cv_color_profile.ColorField(max_length=8, verbose_name='Primary color')),
            ],
            options={
                'db_table': 'app_owner_cv_color_profile',
            },
        ),
        migrations.AlterField(
            model_name='cvdocumentadditional',
            name='type',
            field=models.CharField(choices=[('hobby', 'Hobby'), ('strength', 'Strengths'), ('achievements', 'Achievements'), ('other', 'Other')], max_length=50, verbose_name='Type'),
        ),
    ]
