# Generated by Django 3.1.5 on 2021-04-08 10:10

from django.db import migrations
import portfolio.db.color_field


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0035_auto_20210408_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcolorprofile',
            name='background',
            field=portfolio.db.color_field.ColorField(default='#FFFFFF', max_length=8, verbose_name='Primary background color'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='primary',
            field=portfolio.db.color_field.ColorField(default='#aa3339', max_length=8, verbose_name='Primary color'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='secondary',
            field=portfolio.db.color_field.ColorField(default='#f7f1e1', max_length=8, verbose_name='Secondary color'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='text_primary',
            field=portfolio.db.color_field.ColorField(default='#f7f1e1', max_length=8, verbose_name='Primary text color'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='text_primary_focus',
            field=portfolio.db.color_field.ColorField(default='#f7f1e1', max_length=8, verbose_name='Primary text color - focus'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='text_secondary',
            field=portfolio.db.color_field.ColorField(default='#f7f1e1', max_length=8, verbose_name='Secondary text color'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='text_secondary_focus',
            field=portfolio.db.color_field.ColorField(default='#f7f1e1', max_length=8, verbose_name='Secondary text color - focus'),
        ),
    ]
