# Generated by Django 3.1.5 on 2021-04-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0036_auto_20210408_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='color_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvcolorprofile'),
            preserve_default=False,
        ),
    ]
