# Generated by Django 3.1.5 on 2021-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0037_cv_color_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
