# Generated by Django 3.1.5 on 2021-04-08 11:52

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0035_project_show_on_index'),
        ('app_owner', '0039_auto_20210408_1351'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='cvdocumentskills',
            name='technologies',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='app_projects.Technology', verbose_name='Technologies'),
        ),
    ]
