# Generated by Django 3.1.5 on 2021-04-08 17:33

from django.db import migrations, models
import portfolio.db.color_field


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0040_auto_20210408_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcolorprofile',
            name='text',
            field=portfolio.db.color_field.ColorField(default='#FFFFFF', max_length=8, verbose_name='Text color'),
        ),
        migrations.AddField(
            model_name='cvcolorprofile',
            name='text_focus',
            field=portfolio.db.color_field.ColorField(default='#ffffff', max_length=8, verbose_name='Text focus color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.CharField(blank=True, choices=[('pdf/cv_assymetric.html', 'Asymmetric'), ('pdf/cv_boxes.html', 'Boxes'), ('pdf/cv_clean.html', 'Clean'), ('pdf/cv_diamond.html', 'Diamond'), ('pdf/cv_inverted.html', 'Clean'), ('pdf/cv_quatro.html', 'Quatro'), ('pdf/cv_simple.html', 'Simple')], max_length=255, verbose_name='PDF template'),
        ),
        migrations.AlterField(
            model_name='cvcolorprofile',
            name='background',
            field=portfolio.db.color_field.ColorField(default='#FFFFFF', max_length=8, verbose_name='Background color'),
        ),
    ]
