# Generated by Django 3.1.5 on 2021-04-09 14:35

from django.db import migrations, models
import portfolio.db.color_field


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0041_auto_20210408_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocument',
            name='additional',
        ),
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.CharField(blank=True, choices=[('pdf/cv_asymmetric.html', 'Asymmetric'), ('pdf/cv_boxes.html', 'Boxes'), ('pdf/cv_clean.html', 'Clean'), ('pdf/cv_diamond.html', 'Diamond'), ('pdf/cv_inverted.html', 'Inverted'), ('pdf/cv_quatro.html', 'Quatro'), ('pdf/cv_simple.html', 'Simple')], max_length=255, verbose_name='PDF template'),
        ),
        migrations.AlterField(
            model_name='cvcolorprofile',
            name='background',
            field=portfolio.db.color_field.ColorField(default='#FFFFFF', max_length=8, verbose_name='Base background color'),
        ),
        migrations.AlterField(
            model_name='cvcolorprofile',
            name='text',
            field=portfolio.db.color_field.ColorField(default='#FFFFFF', max_length=8, verbose_name='Base text color'),
        ),
        migrations.AlterField(
            model_name='cvcolorprofile',
            name='text_focus',
            field=portfolio.db.color_field.ColorField(max_length=8, verbose_name='Base text focus color'),
        ),
    ]
