# Generated by Django 3.1.5 on 2021-04-09 14:37

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0042_auto_20210409_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='additional',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='app_owner.CVDocumentAdditional', verbose_name='Additional'),
        ),
    ]
