# Generated by Django 3.1.5 on 2021-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0045_auto_20210409_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocumentexperiencejobtranslation',
            old_name='description',
            new_name='description_list',
        ),
        migrations.AddField(
            model_name='cvdocumentexperiencejobtranslation',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='Job position'),
            preserve_default=False,
        ),
    ]
