# Generated by Django 3.1.5 on 2021-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0046_auto_20210409_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocumentexperiencejobtranslation',
            name='description_list',
        ),
        migrations.AddField(
            model_name='cvdocumentexperiencejobtranslation',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
