# Generated by Django 3.1.5 on 2021-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0047_auto_20210409_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdocumenteducationschool',
            name='to_date',
            field=models.DateField(blank=True, verbose_name='To'),
        ),
    ]
