# Generated by Django 3.1.5 on 2021-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0048_auto_20210409_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdocumenteducationschool',
            name='to_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='cvdocumentexperiencejob',
            name='to_date',
            field=models.DateField(blank=True, verbose_name='To'),
        ),
    ]
