# Generated by Django 3.1.5 on 2021-04-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0050_auto_20210409_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocument',
            name='additional',
        ),
    ]
