# Generated by Django 3.1.5 on 2021-04-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0052_cvdocument_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocument',
            name='additional',
        ),
        migrations.CreateModel(
            name='CVDocument_additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.cvdocument')),
                ('cv_document_additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_owner.cvdocumentadditional')),
            ],
            options={
                'verbose_name': 'Additional information',
            },
        ),
    ]
