# Generated by Django 3.1.5 on 2021-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0053_auto_20210409_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='additional',
            field=models.ManyToManyField(blank=True, through='app_owner.CVDocument_additional', to='app_owner.CVDocumentAdditional', verbose_name='Additional'),
        ),
    ]
