# Generated by Django 3.1.5 on 2021-04-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0058_auto_20210410_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVDocumentPersonal',
            new_name='CVDocumentContact',
        ),
        migrations.RenameModel(
            old_name='CVDocumentPersonalTranslation',
            new_name='CVDocumentContactTranslation',
        ),
        migrations.AlterModelTable(
            name='cvdocumentcontact',
            table='app_owner_cv_doc_contact',
        ),
        migrations.AlterModelTable(
            name='cvdocumentcontacttranslation',
            table='app_owner_cv_doc_contact_translation',
        ),
    ]
