# Generated by Django 3.1.5 on 2021-04-10 11:59

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0059_auto_20210410_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocumentPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=255, verbose_name='Identification name')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentphoto', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'CV Document personal',
                'db_table': 'app_owner_cv_doc_personal_data',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='cvdocumentsummarytranslation',
            name='position_title',
        ),
        migrations.CreateModel(
            name='CVDocumentPersonalTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('position_title', models.CharField(max_length=255, verbose_name='Position title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='app_owner.cvdocumentpersonal')),
            ],
            options={
                'verbose_name': 'CV Document personal Translation',
                'db_table': 'app_owner_cv_doc_personal_data_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
