# Generated by Django 3.1.5 on 2021-04-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0060_auto_20210410_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocument',
            old_name='personal',
            new_name='contact',
        ),
    ]
