# Generated by Django 3.1.5 on 2021-04-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0062_auto_20210410_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVDocumentPersonalContacts',
            new_name='CVDocumentContactContacts',
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentcontact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentpersonal', verbose_name='Personal'),
        ),
    ]
