# Generated by Django 3.1.5 on 2021-04-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0065_cvdocumenteducationtranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvdocumentcontactcontacts',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='cvdocumenteducationschool',
            options={'ordering': ['-from_date'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
    ]
