# Generated by Django 3.1.5 on 2021-04-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0066_auto_20210410_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvdocumentcontactcontacts',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelTable(
            name='cvdocumentcontactcontacts',
            table='app_owner_cv_doc_contact_contacts_rel',
        ),
    ]
