# Generated by Django 3.1.5 on 2021-04-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0068_auto_20210410_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocumentadditionaltranslation',
            old_name='title',
            new_name='section_title',
        ),
    ]
