# Generated by Django 3.1.5 on 2021-04-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0069_auto_20210410_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdocumenteducationschooltranslation',
            old_name='school',
            new_name='name',
        ),
    ]
