# Generated by Django 3.1.5 on 2021-04-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0070_auto_20210410_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocumentexperiencejob',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Address'),
        ),
    ]
