# Generated by Django 3.1.5 on 2021-04-10 23:30

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0071_cvdocumentexperiencejob_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocumentAgreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=255, verbose_name='Identification name')),
            ],
            options={
                'verbose_name': 'Cv document agreements',
                'verbose_name_plural': 'Cv document agreements',
                'db_table': 'app_owner_cv_doc_agreements',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='agreements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_owner.cvdocumentagreements', verbose_name='Rodo agreements'),
        ),
        migrations.CreateModel(
            name='CVDocumentAgreementsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.TextField(verbose_name='Agreements text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='app_owner.cvdocumentagreements')),
            ],
            options={
                'verbose_name': 'Cv document agreements Translation',
                'db_table': 'app_owner_cv_doc_agreements_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
