# Generated by Django 3.1.5 on 2021-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0073_cv_on_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='Link on main page'),
        ),
    ]
