# Generated by Django 3.1.5 on 2021-04-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0074_auto_20210417_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='on_main_page',
            field=models.BooleanField(default=False, verbose_name='Link on main page'),
        ),
    ]
