# Generated by Django 3.1.5 on 2021-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0075_cvdocument_on_main_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvcolorprofile',
            options={'verbose_name': 'Cv Color Profile', 'verbose_name_plural': 'Cv Color Profiles'},
        ),
        migrations.AddField(
            model_name='cv',
            name='reset_slug',
            field=models.BooleanField(default=False),
        ),
    ]
