# Generated by Django 3.1.5 on 2021-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_owner', '0078_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Contact protected'),
        ),
    ]
