from .contact import *
from .contact_img import *
from .cv import *
from .cv_doc import *
from .cv_doc_additional import *
from .cv_doc_personal import *
from .cv_doc_edu import *
from .cv_doc_exp import *
from .cv_doc_skills import *
from .cv_doc_summary import *
from .cv_doc_photo import *
from .cv_color_profile import *